### ISSUE TITLE
JUnit 4 inner class execution order seems to be unenforceable

### ISSUE THREAD

**Issue by ferencDobi** [Codewars/codewars-runner-cli#680] opened 2019-01-23 08:04 UTC
#### Describe the bug

I tried using inner classes to group my tests together as Fixed and Random and I wanted to make sure the fixed tests were executed first. However, their execution order seems to be pseudo-random and unenforceable. When I tried using a Suite runner, the inner classes were executed in order by the runner, however, every test executed twice, once as part of the suite, once as part of separate test classes (the three groups, Fixed, Random, and the suite containing both, were ordered randomly).

#### To Reproduce

Here are the orders my classes were executed in depending on their name:
Missions.Fixed (2nd), Missions.Random (1st)
Missions.Rixed (1st), Missions.Fandom (2nd)
Missions.Static (2nd), Missions.Random (1st)
Tests.Fixed (1st), Tests.Random (2nd)

The code I used when I tried to run the tests as a suite which resulted in the duplication of tests:
```java
@RunWith(Suite.class)
@SuiteClasses({ Missions.Fixed, Missions.Random })
public class Missions {
  public static class Fixed {}
  public static class Random {}
}
```

#### Expected Behavior

It would be nice if you could somehow force the order of your test groups, while not duplicating them.
From my example, you can see that I eventually found a name for my classes that were both descriptive and resulted in the desired order, but it was an aggravating process.

**Comment by kazk** [comment] 2019-01-23 21:16
I don't think it's possible using JUnit 4.

> By design, JUnit does not specify the execution order of test method invocations.
> https://github.com/junit-team/junit4/wiki/test-execution-order

I think this applies to tests using classes as well.

They added some options in 4.11

> From version 4.11, JUnit will by default use a deterministic, but not predictable, order (MethodSorters.DEFAULT). To change the test execution order simply annotate your test class using @FixMethodOrder and specify one of the available MethodSorters:
>
> `@FixMethodOrder(MethodSorters.JVM)`: Leaves the test methods in the order returned by the JVM. This order may vary from run to run.
>
> `@FixMethodOrder(MethodSorters.NAME_ASCENDING)`: Sorts the test methods by method name, in lexicographic order.


and we use 4.12 so that should be available.

---

We actually also support JUnit 5.
So you might be able to achieve what you want using [OrderAnnotation](https://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-test-execution-order).

Make sure to rewrite your test to use JUnit 5 APIs.

JUnit 5 allows grouping tests and nesting them. [TestingAStackDemo.java](https://github.com/junit-team/junit5/blob/696090182209d0bdf5070cc2534c4d2e5422ed25/documentation/src/test/java/example/TestingAStackDemo.java) outputs

![image](https://user-images.githubusercontent.com/639336/51637229-037d6c80-1f10-11e9-8462-a3bc9f585d68.png)

**Comment by kazk** [comment] 2019-01-23 21:18
Closing because it's not a bug. Feel free to comment if you have any questions.

**Closed by kazk** 2019-01-23 21:18 UTC
Labels: invalid, language/java

**Comment by ferencDobi** [comment] 2019-01-24 11:18
Thank you! Didn't know JUnit 5 was available. Maybe the reference code should be updated to reflect that.

**Comment by kazk** [comment] 2019-01-24 18:44
It's currently _hidden_ because it felt like a hack. I wanted to differentiate `junit` (JUnit 4) and `junit5`, but Codewars doesn't support multiple test frameworks for a language at the moment. I also didn't want to make it confusing for average users.

This works because JUnit 5's API is used to discover and run JUnit 4 tests under the hood. I'm going to try my best to not to break in the future so it should be safe to use.

**Comment by javatlacati** [comment] 2019-01-30 05:09
You should be able to configure the execution order of test using JUnit4 with `FixMethodOrder` annotation.

```
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class Fixed {
}
```
