### ISSUE TITLE
Add Agda

### ISSUE THREAD

**Issue by MarisaKirisame** [Codewars/codewars-runner-cli#719] opened 2019-03-07 21:25 UTC
https://en.wikipedia.org/wiki/Agda_(programming_language)
https://github.com/agda/agda
Version: 2.5.4.2

agda is a dependently typed language that is like idris. however, it has support for universe polymorphism and homotopy type theory.

---

- [x] Install `agda` (`Agda-2.5.4.2.20190217`, use `2.6.0` when released)
- [x] [`agda-stdlib`](https://github.com/agda/agda-stdlib) (https://github.com/agda/agda-stdlib/commit/2c27122a9b5d0acb8e97d9c094a4115b56fa9278)
- [x] [`cubical`](https://github.com/agda/cubical) (https://github.com/agda/cubical/commit/14e92653ca3d324b793d193e9c292deca9480f8e)
- [x] Testing (`agda module.agda`)
- [x] Logo for icon
  - Official logo doesn't seem to exist yet (https://github.com/agda/agda/issues/2823)
  - Found these:
    - https://github.com/UlfNorell/agda-logo
    - https://github.com/jmchapman/agda-logos
- [x] CodeMirror mode. Use Haskell for now.

**Comment by ice1000** [comment] 2019-03-07 22:36
No!!! 2.6.0 Please!!

**Comment by ice1000** [comment] 2019-03-07 22:37
And Cubical Agda/stdlib please!

**Comment by DonaldKellett** [comment] 2019-03-08 05:11
Took me a while but I seemed to have stumbled upon [what looks like a testing framework for Agda](https://github.com/marco-vassena/testing-agda).  Not sure if it is (easily) customizable though (or even a testing framework in the usual sense) 😛

**Comment by ice1000** [comment] 2019-03-08 05:20
Agda is very safe by default so a type alias in the test case may probably be enough (because a by-default total language is entirely not suitable for writing something that cannot easily be tested with type ristrictions).

**Comment by ice1000** [comment] 2019-03-08 05:21
But I feel like writing tests is also important.

**Comment by MarisaKirisame** [comment] 2019-03-08 05:31
@DonaldKellett I'd say we dont really need one. Agda can evaluate code while typechecking, so you can write test that wont typecheck if the result is wrong.

**Comment by MarisaKirisame** [comment] 2019-03-08 05:33
(random testing is still a good idea, but that library is incredibly outdated, has no star, and probably do not has random testing. we should leave it out until we found one.)

**Comment by DonaldKellett** [comment] 2019-03-08 06:19
@MarisaKirisame Random testing may not be required if Agda's type system is expressive enough and doesn't provide any escape hatches like Haskell/Idris/PureScript does, but AFAIK Codewars still needs *some* kind of testing framework (like specdris) where basic assertions such as ``3 + 5 `shouldBe` 8`` can be written and its results printed to STDOUT, e.g. `<PASSED::>Test Passed - Value == 8\n`.

**Comment by DonaldKellett** [comment] 2019-03-08 06:22
On the other hand @kazk , would it be possible to special-case certain languages in the runner such that those languages need only compile to be considered as "passed"?  That could open up whole new classes of languages previously impossible to include on Codewars such as Coq where AFAIK there's no concept of printing stuff to STDOUT or interacting with the outside world.

**Comment by MarisaKirisame** [comment] 2019-03-08 06:23
@DonaldKellett it can be written like this
test : 3 + 5 ≡ 8
test = refl

test_fail : 3 + 5 ≡ 9
test_fail = refl -- this will not work

**Comment by MarisaKirisame** [comment] 2019-03-08 06:25
@DonaldKellett I think the point is we dont need to special case. The test will just always pass after it typecheck. if there is error then the test will be reported.

**Comment by kazk** [comment] 2019-03-08 06:42
@DonaldKellett that should be possible. Just always have one implicit test case ("program compiles") that's marked as passed if the exit code is zero.

So the output will be either:

- `<PASSED::>`: Successfully compiled
- `<FAILED::>`: Failed to compile. Show error messages that's (hopefully) helpful enough to identify the cause

@MarisaKirisame yeah, that's the idea. Just slightly different from other languages for not having a test framework producing the required outputs.

**Comment by MarisaKirisame** [comment] 2019-03-08 06:52
Just to state the obvious, we should not print the error message for failed actual test.
Cause if we do so ppl can read what went wrong and fix them one by one (by special casing on the input).

**Comment by DonaldKellett** [comment] 2019-03-08 07:01
> Cause if we do so ppl can read what went wrong and fix them one by one (by special casing on the input).

But I thought this was what the type system was meant to prevent?  E.g. you can't prove A + B = B + A in Coq and related languages by special casing on certain values of A and B.

**Comment by kazk** [comment] 2019-03-08 07:15
> Just to state the obvious, we should not print the error message for failed actual test.

So we just say it failed and don't show anything else? Wouldn't that be too frustrating?
Maybe we're talking about something different.

**Comment by ice1000** [comment] 2019-03-08 11:47
Special mention: @gallais

**Comment by ice1000** [comment] 2019-03-08 11:50
> Just to state the obvious, we should not print the error message for failed actual test.
> Cause if we do so ppl can read what went wrong and fix them one by one (by special casing on the input).

No! No! No! No! No! You should write the most general type signature to kick the hardcode men :devil_man:.

**Comment by MarisaKirisame** [comment] 2019-03-08 15:34
@DonaldKellett there are two way to test agda on codewar.
0: force user to prove he's correct, so you do not need any input/output test
1: test that output match input for a few example.
In the latter case, if all the test is visible, one can just cheese by returning a function that only work on the test case

**Comment by ice1000** [comment] 2019-03-08 16:36
that's considered bad test because it's easily hackable anyway

**Comment by kazk** [comment] 2019-03-09 03:17
I'm starting to play with Agda 2.5.4.2 and agda-stdlib.

Can anyone provide some (minimum) examples that I can use to experiment with?

- test (not really, but the part where kata author writes and requires)
- incomplete solution
- complete solution

If I'm understanding correctly, we don't need to do `agda --compile` right? `agda --compile` seems to generate Haskell code after type checking and compile that into an executable. We only care about the result of the type check.

**Comment by ice1000** [comment] 2019-03-09 04:55
Initial solution (load this in Emacs, you see hints about all incomplete parts!)

```agda
{-# OPTIONS --safe #-}
module Example where
open import Agda.Builtin.Equality

_⇆_ : {A : Set} {a b c : A} → a ≡ b → b ≡ c → a ≡ c
a ⇆ b = ?
```

Complete solution:

```agda
{-# OPTIONS --safe #-}
module Example where
open import Agda.Builtin.Equality

_⇆_ : {A : Set} {a b c : A} → a ≡ b → b ≡ c → a ≡ c
refl ⇆ refl = refl
```

Test:

```agda
{-# OPTIONS --safe #-}
module Test where
open import Example

check : {A : Set} {a b c : A} → a ≡ b → b ≡ c → a ≡ c
check = _⇆_
```

**Comment by ice1000** [comment] 2019-03-09 04:57
> If I'm understanding correctly, we don't need to do agda --compile right?

Yup. `agda File.agda` is already what we want. There're several kinds of library-importing strategies like using CLI arguments or using `.agda/` (see https://agda.readthedocs.io/en/latest/tools/package-system.html)

**Comment by ice1000** [comment] 2019-03-09 05:00
However, I strongly recommend Agda 2.6.0 (which will be released soon), or simply track the master Agda (and use the experimental branch of the stdlib) because there's a killer feature called cubical model support and the status of 2.6.0 is very close to a release.
If you're happy with updating to 2.6.0 *after* the release, ignore the comment.

**Comment by kazk** [comment] 2019-03-09 07:21
Initial solution outputs the following with exit code `1`
```
Checking ExampleTest (/workspace/agda/ExampleTest.agda).
 Checking Agda.Builtin.Equality (/opt/agda/share/x86_64-linux-ghc-8.4.3/Agda-2.5.4.2/lib/prim/Agda/Builtin/Equality.agda).
 Checking Example (/workspace/agda/Example.agda).
/workspace/agda/ExampleTest.agda:5,13-20
Module cannot be imported since it has open interaction points
(consider adding {-# OPTIONS --allow-unsolved-metas #-} to this
module)
when scope checking the declaration
  open import Example
```

Complete solution outputs the following with exit code `0`
```
Checking ExampleTest (/workspace/agda/ExampleTest.agda).
 Checking Agda.Builtin.Equality (/opt/agda/share/x86_64-linux-ghc-8.4.3/Agda-2.5.4.2/lib/prim/Agda/Builtin/Equality.agda).
 Checking Example (/workspace/agda/Example.agda).
```

@ice1000 do you have something that can be imported, but fails? I'm trying to figure out what should be shown to the user on failure.

---

> However, I strongly recommend Agda 2.6.0 (which will be released soon)

Yeah, I'm just trying things out and 2.5.x was just easier to get started.

**Comment by ice1000** [comment] 2019-03-09 07:44
Either **remove the `--safe` line in the test module** and use this
```agda
{-# OPTIONS --allow-unsolved-metas #-}
module Example where
open import Agda.Builtin.Equality

_⇆_ : {A : Set} {a b c : A} → a ≡ b → b ≡ c → a ≡ c
a ⇆ b = ?
```

Or use another which does not need you to change the test module:

```agda
{-# OPTIONS --safe #-}
module Example where
open import Agda.Builtin.Equality

_⇆_ : {A : Set} {a b c : A} → a ≡ a → a ≡ a → a ≡ a
refl ⇆ refl = refl
```

**Comment by ice1000** [comment] 2019-03-09 07:53
Agda's semantics of `--safe`: any unsafe operations, like importing some non-`--safe` modules, `postulate`, `{-# TERMINATING #-}` pragma, anything (known) that may either crash the compiler or potentially damage anything at runtime will be forbidden.
This makes it a lot easier to be used as an "it type-checks, it works" PL (at least comparing to Idris).

**Comment by ice1000** [comment] 2019-03-09 07:55
Special mention: @DonaldKellett 

I feel like I have a lot of things to be put to CW when Agda (2.6.0) is launched :).

**Comment by kazk** [comment] 2019-03-09 08:07
We need to disallow `--allow-unsolved-metas` then. By setting that option, it now has exit code `0` without any warnings.

```
Checking ExampleTest (/workspace/agda/ExampleTest.agda).
 Checking Agda.Builtin.Equality (/opt/agda/share/x86_64-linux-ghc-8.4.3/Agda-2.5.4.2/lib/prim/Agda/Builtin/Equality.agda).
 Checking Example (/workspace/agda/Example.agda).
```

This will be considered passed and unlike Idris, we can't check the output for a warning.

Doing `agda --safe ExampleTest.agda` failed saying `--allow-unsolved-metas` can't be used with `--safe` option so maybe we should always use `agda --safe`. Is there any downsides for always using `agda --safe`?

---

The one with different type outputs the following with exit code `1`.
```
Checking ExampleTest (/workspace/agda/ExampleTest.agda).
 Checking Agda.Builtin.Equality (/opt/agda/share/x86_64-linux-ghc-8.4.3/Agda-2.5.4.2/lib/prim/Agda/Builtin/Equality.agda).
 Checking Example (/workspace/agda/Example.agda).
/workspace/agda/ExampleTest.agda:8,9-12
.b != .a of type .A
when checking that the expression _⇆_ has type
.a ≡ .b → .b ≡ .c → .a ≡ .c
```

**Comment by Bubbler-4** [comment] 2019-03-09 08:23
> Agda's semantics of `--safe`: any unsafe operations, like **importing some non-`--safe` modules**... will be forbidden.

This sounds like, if I use `--safe` on test code, it automatically forces the solution code to use `--safe` too. If so, I guess we don't need to apply `--safe` runner-wise; we just explicitly put an options pragma when needed.

**Comment by kazk** [comment] 2019-03-09 08:26
@Bubbler-4 It passed even with `{-# OPTIONS --safe #-}` in test file. I'm guessing `--allow-unsolved-metas` makes the module considered "safe", so importing it is "safe".

**Comment by gallais** [comment] 2019-03-09 08:38
> It passed even with {-# OPTIONS --safe #-} in test file. I'm guessing --allow-unsolved-metas makes the module considered "safe", so importing it is "safe".

There was a long standing bug meaning that option consistency was not checked
(agda/agda#2487). It has been fixed in the upcoming 2.6.0.

**Comment by kazk** [comment] 2019-03-09 22:18
@ice1000 @gallais 
Is the error always formatted like the following?

```
/path/to/module.agda:line,from_col-to_col
error message line 1
error message line 2
...
/path/to/module.agda:line,from_col-to_col
error message line 1
```

If so, I think we can output something like the following on failure:
![image](https://user-images.githubusercontent.com/639336/54077972-55d2dc80-4275-11e9-8e47-f265a7cc2ab5.png)

or hide the location
![image](https://user-images.githubusercontent.com/639336/54077996-9894b480-4275-11e9-9821-8bc97b7e099b.png)


I'd like to avoid having a huge wall of text like

![image](https://user-images.githubusercontent.com/639336/54077930-a85fc900-4274-11e9-87db-db93adb9a15a.png)

or

![image](https://user-images.githubusercontent.com/639336/54077942-d0e7c300-4274-11e9-9c7d-853c1c41c41e.png)


---

On success, we'll show something like

![image](https://user-images.githubusercontent.com/639336/54078030-fa551e80-4275-11e9-987e-0b9746ffa736.png)

**Comment by kazk** [comment] 2019-03-10 04:15
I think I've got it mostly working, but we can't use `agda-stdlib` yet. `v0.17` doesn't work with `--safe` and I get the following for `master`:

```
/opt/agda/agda-stdlib/src/Data/Empty.agda:16,1-66
COMPILE pragma not allowed in safe mode.
when scope checking the declaration
  open import Data.Empty hiding (⊥-elim)
```

**Comment by ice1000** [comment] 2019-03-10 07:32
For icon:

agda/agda#2823
https://wiki.portal.chalmers.se/agda/pmwiki.php?n=AIMXXIII.LogoCompetition

**Comment by gallais** [comment] 2019-03-10 07:51
> Is the error always formatted like the following?

We are using a [pretty printer](https://github.com/agda/agda/blob/66b8fc33d5d4e19edc0bbd1b23a00719dc2ce0d9/src/full/Agda/TypeChecking/Errors.hs#L494) so everything should indeed follow the same format.

However, we need to be a bit careful: Agda also outputs warnings which do not
necessarily mean the code is broken. So you may want to pass `-Wignore` so that
you don't get any of these.

**Comment by kazk** [comment] 2019-03-10 09:17
All G one looks cool!

![image](https://user-images.githubusercontent.com/639336/54082535-ff44bd00-42cb-11e9-8b62-b602bf34c0ee.png)

Might be difficult to see in icon size, but it looks different from other language icons we have so it can work. Can we use this?

I couldn't vectorize the other one so I couldn't compare.

---

> Agda also outputs warnings which do not necessarily mean the code is broken. So you may want to pass `-Wignore` so that you don't get any of these.

Hmm, currently the output is handled differently depending on the exit code. So when the exit code is zero and the warning is outputted, it should be displayed like

![image](https://user-images.githubusercontent.com/639336/54082730-0a4d1c80-42cf-11e9-82da-4a92f1b13dad.png)
![image](https://user-images.githubusercontent.com/639336/54082720-f1dd0200-42ce-11e9-8f78-cff5442a87da.png)
collapsed by default so it shouldn't be a problem in this case.

But warnings and errors are mixed when the exit code is non-zero and warnings are grouped under "Issues" so that can be misleading :thinking: I'll adjust this later if it gets in the way and depending on what users think.

**Comment by kazk** [comment] 2019-03-11 06:06
Agda is now available on Codewars! Thanks for all the help! The actual language version is `2.5.4.2.20190217` which I'll update to `2.6.0` once released.


This should be considered an alpha release and I need help testing it. For example, I didn't test the output much because I don't know Agda and it was difficult for me to come up with variations to produce different errors.  I installed/type checked `standard-library` (`experimental`) and `cubical` (`master`), but only confirmed that it can be imported.

Any feedback is appreciated as always :)


For the editor, we're using CodeMirror's Haskell mode and it's not great :(

![image](https://user-images.githubusercontent.com/639336/54101693-2a89e380-4382-11e9-90dc-d4feaf4c49cf.png)

If any of you want to try making Agda mode for CodeMirror, that'll be great.

**Closed by kazk** 2019-03-11 06:06 UTC
Labels: request/language

**Comment by kazk** [comment] 2019-03-11 23:19
We have some Agda challenges now :tada:

![image](https://user-images.githubusercontent.com/639336/54164223-193fe600-4419-11e9-945d-8d48f1e0eccb.png)

https://www.codewars.com/kata/search/agda

Also checkout the new ["Thorem Proving" tag](https://www.codewars.com/kata/search/my-languages?q=&tags=Theorem+Proving).
