### ISSUE TITLE
Coffeescript: Tests not executed

### ISSUE THREAD

**Issue by siebenschlaefer** [Codewars/codewars-runner-cli#406] opened 2017-04-30 20:21 UTC
I was able to solve https://www.codewars.com/kata/check-and-mate and
https://www.codewars.com/kata/5313b713bb244a0eb20001fe by just executing a successful test:

```
Test.expect true
```

A solution of just

```
# comment
```

results in ``Time: 311ms Passed: 0 Failed: 1 Errors: 1``.

This might be because both use embedded Javascript (with `) for their tests and it looks like that code is not executed.

**Comment by DonaldKellett** [comment] 2017-05-01 02:42
I just tested the Kata [Check and Mate](https://www.codewars.com/kata/check-and-mate) *as a guest* and confirmed that this hack works for CoffeeScript but not JavaScript.

**Comment by kazk** [comment] 2017-07-19 08:24
I think this is caused by tests written as embedded JavaScript in the form:

```coffeescript
`
test();
`
```

```coffeescript
# CoffeeScript test from "Number-like counter" kata (simplified)
`
var c = new Counter();
Test.expect(c == 0, "c == 0 was false");
`
```

Reproducible with
```coffeescript
add = (a, b) -> a + b
```

```coffeescript
`
Test.assertEquals(add(1, 1), 2);
`
```

![image](https://user-images.githubusercontent.com/639336/28353780-131a1a6a-6c12-11e7-93a7-9f8a4c4b68bd.png)

```coffeescript
add = (a, b) -> a + b
# adding
Test.expect true
# makes this pass
```
![image](https://user-images.githubusercontent.com/639336/28354287-2ff4db00-6c14-11e7-936a-6d31144a950a.png)

I'm guessing having no test at all is considered a failure and adding one passing test works around it.

---

This issue only happens when the first backtick is followed by LF.
```coffeescript
`Test.assertEquals(add(1, 1), 2);` # ok

`Test.assertEquals(add(1, 1),
2);`                               # ok

`
Test.assertEquals(add(1, 1), 2);
`                                  # not ok
`
Test.assertEquals(add(1, 1), 2);`  # not ok
```
![image](https://user-images.githubusercontent.com/639336/28354753-eb1c0ace-6c15-11e7-8905-6dee65ca7de9.png)

This is because CoffeeScript runner [combines](https://github.com/Codewars/codewars-runner-cli/blob/fc8b6fec3b36ee07fa406cdd30ac077cbd2460ec/lib/runners/coffeescript.js#L26-L41) the code like the following:

```coffeescript
Test.handleError ->
  # setup
  # solution
  do ->
    # tests
```

and 

```coffeescript
`
Test.assertEquals(add(1, 1), 2);`
```
is
```js
return
Test.assertEquals(add(1, 1), 2);;
```
inside `do ->`.

Also, more than one statement won't work. You can work around with

```coffeescript
`(function() {
Test.assertEquals(add(1, 1), 2);
Test.assertEquals(add(1, 2), 3);
// ...
})()`
```

Maybe this used to work on older version of CoffeeScript, but I don't know the language enough to tell.

---

By the way, is this common on Codewars? Just wrapping the original JavaScript tests with backticks to have CoffeeScript *translation*?

**Comment by kazk** [comment] 2017-08-03 21:33
Closing this because I'm not sure how to fix this from our end and workarounds are available.

**Closed by kazk** 2017-08-03 21:33 UTC
Labels: bug, help wanted
