### ISSUE TITLE
Add Factor support

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars-runner-cli#626] opened 2018-06-15 06:58 UTC
Although little known, Slava Pestov before he started working on Swift, developed a very neat language called Factor. As a concatenative language it builds upon Forth's, Lisp's, and Smalltalk's heritage, but has many modern concepts incorporated. For developers it offers the possibility to learn about these concepts. Pestov's Google TechTalk is an inspiring starting point (https://youtu.be/f_0QlhYlS8g). Factor compiler etc. can be found at http://factorcode.org/.

**Comment by kazk** [comment] 2018-06-15 18:07
Is there a test framework we can use?
The fastest way to get this is to provide us some examples like this [Fortran](https://github.com/Codewars/codewars-runner-cli/issues/553) contribution.

**Comment by nomennescio** [comment] 2018-07-03 10:16
Will come back to this!

**Comment by nomennescio** [comment] 2018-07-03 10:30
Unit testing is part of the language:

http://docs.factorcode.org/content/article-tools.test.html

Unit tests for a vocabulary are placed in test files in the same directory as the vocabulary source file (see Vocabulary loader). Two possibilities are supported:
•	Tests can be placed in a file named vocab-tests.factor
•	Tests can be placed in files in the tests subdirectory

If the test harness needs to define words, they should be placed in a vocabulary named vocab.tests where vocab is the vocab being tested.

http://docs.factorcode.org/content/word-test%2Ctools.test.html

Runs unit tests for the vocabulary named prefix and all of its child vocabularies.

--

As for examples, Factor is self-hosting, and has unit tests for all its libraries

E.g. the Math vocabulary:
https://github.com/factor/factor/tree/master/core/math

is implemented in
https://github.com/factor/factor/blob/master/core/math/math.factor

with unit tests in
https://github.com/factor/factor/blob/master/core/math/math-tests.factor

**Comment by nomennescio** [comment] 2018-07-03 10:49
As for running Factor from the command-line (inside Codewars runner framework)

See
http://docs.factorcode.org/content/article-command-line.html

Factor command line usage:
factor [VM args...] [script] [args...]
Zero or more VM arguments can be passed in, followed by an optional script file name. If the script file is specified, it will be run on startup using run-script.

Instead of running a script, it is also possible to run a vocabulary; this invokes the vocabulary's MAIN: word:
factor [system switches...] -run=<vocab name>

http://docs.factorcode.org/content/word-run-script%2Ccommand-line.html

Parses the Factor source code stored in a file and runs it. The initial vocabulary search path is used. If the source file contains a MAIN: declaration, the main entry point of the file will be also be executed. Loading messages will be suppressed.

**Comment by nomennescio** [comment] 2018-07-03 10:56
To make this work in a Codewars context, probably multiple files are needed for each of the 'setup', 'preloaded', 'sample tests', 'tests', and 'solution' parts, and probably an extra file to glue it together.

As 'MAIN:' is the main entry, it should probably be part of the glue file, which then call (sample) tests, and the solution (setup) is probably a child vocabulary. Preloaded could be another child vocabulary loaded from the glue file.

**Comment by kazk** [comment] 2018-07-03 23:38
Thanks! This is very helpful. I won't be able to work on this any time soon, but will look into it.

**Comment by nomennescio** [comment] 2018-07-04 09:12
Can I help?

**Comment by kazk** [comment] 2018-07-04 22:05
https://github.com/Codewars/codewars-runner-cli/issues/625#issuecomment-402565208

**Comment by nomennescio** [comment] 2018-07-31 10:19
Factor has just released version 0.98 (4 years after the previous release), which is a HUGE step forward.
There is no Debian/Ubuntu package for apt-get, but installing is still pretty painless (adapt installation directories/paths where necessary)

```shell
FILE=factor-linux-x86-64-0.98.tar.gz
[ -f $FILE ] || wget -nd http://downloads.factorcode.org/releases/0.98/$FILE
[ -d factor ] || tar -zxf $FILE
```

Hope this is good enough.

**Comment by kazk** [comment] 2018-08-07 02:53
I was able to build an image and run hello world. We still need to figure out test with Codewars output.

**Comment by nomennescio** [comment] 2018-08-07 15:01
Very good! I'm continuing my experimentations to see how to best interface with Codewars using the existing Factor unit-test.

**Comment by nomennescio** [comment] 2018-09-03 13:58
I've committed a first version of example usage of how to setup the file structure, use the existing unit test framework, and how to invoke Factor from any directory. The unit test does not yet output format suitable for Codewars runners, that will be the next step.

https://github.com/nomennescio/coderunner-factor.git

**Comment by nomennescio** [comment] 2019-08-18 16:43
Finally found some time to dig in the Factor test framework. 

For now I already committed an update that shows how to use the existing unit-test framework in case of failures. It gets messy.

It looks like the existing unit-test is not suitable, as it assumes a Factor GUI environment. Therefore I will be writing a test framework from scratch, suitable for Codewars, and somewhat similar to the Forth framework. Because Factor is fully typed, it will probably have support for primitive types built-in already.

**Comment by nomennescio** [comment] 2019-08-18 22:26
Initial version of Testest framework pushed with some simple tests. The 'unit-test' word should work about the same as Factor's own tools.test framework.

**Comment by nomennescio** [comment] 2019-08-19 02:36
Changed syntax to be the same as for the Forth test framework.

**Comment by nomennescio** [comment] 2019-08-19 16:21
Added test suite to regression test Testest framework

**Comment by nomennescio** [comment] 2019-08-20 12:56
@kazk I think the framework is now in a state where experimental support for Factor on Codewars can be considered.

**Comment by kazk** [comment] 2019-08-20 17:28
Cool. I'm busy this week, but will take a look when I can.

**Comment by kazk** [comment] 2019-08-23 02:43
@nomennescio can you change

```
<FAILED::>Test Failed
Expected :
1
, but got :
0
```
to
```
<FAILED::>Test Failed<:LF:>Expected :<:LF:>1<:LF:>, but got :<:LF:>0
```
?

Basically replace `\n` with `<:LF:>`.

**Comment by nomennescio** [comment] 2019-08-23 05:58
Will do that

**Comment by kazk** [comment] 2019-08-23 17:03
Codewars' output command (all the `<FAILED::>`,`<PASSED::>`, etc) must be single line. Only internal linefeeds should be replaced, the final linefeed should be kept.

**Comment by nomennescio** [comment] 2019-08-24 05:22
Done. Now also includes separated user redefinable custom test messages.

**Comment by kazk** [comment] 2019-08-24 20:06
![image](https://user-images.githubusercontent.com/639336/63642114-1ce5c300-c66f-11e9-9ebb-e091f8792540.png)
Maybe it looks better if `Expected` was moved to next line.
![image](https://user-images.githubusercontent.com/639336/63642125-72ba6b00-c66f-11e9-8c82-b05838246eb6.png)
or remove `Test Failed`
![image](https://user-images.githubusercontent.com/639336/63642130-8ebe0c80-c66f-11e9-87ae-2ced3ef9c930.png)
I think the last one looks the best.

**Comment by Steffan153** [comment] 2019-08-24 21:39
IMO, I think it would probably look best if it was all on 1 line, and without spaces before colons. :)

**Comment by kazk** [comment] 2019-08-24 21:52
I agree about the spaces before the colons, but single line can be difficult to see when it gets long depending on how the contents of the stack are displayed (how they're delimited, if it's surrounded by anything, etc). The repo contains examples with multiple items.

![image](https://user-images.githubusercontent.com/639336/63643041-d9df1c00-c67d-11e9-97fe-cf1f97a85b78.png)

I'm not too concerned about the formatting at this point because I don't know how or if other data types are displayed. We can change it later as we find issues.

**Comment by nomennescio** [comment] 2019-08-26 10:48
The  formatting of items on a separate line is a feature of Factor, which support arbitrarily nested non-homogeneous structures. It will pretty print such nested structures in a well-known short format, on a single line.

Using custom formatting, it's always possible to change the default formatting in a specific test. I'm still working on that.

**Comment by nomennescio** [comment] 2019-08-26 21:27
Delivered update on custom formatting with test code. Not entirely satisfied with custom error handling yet.

**Comment by nomennescio** [comment] 2019-08-27 20:29
Added test to run test cases to assert equality for different Factor types. So yes, the Testest framework supports multiple types without any change in syntax.

**Comment by kazk** [comment] 2019-08-30 04:13
@nomennescio can we relicense to MIT like ttester-codewars (will mention that you're the author/copyright holder)? Then I'll create a repository https://github.com/Codewars/testest with it and add you there like ttester.

**Comment by nomennescio** [comment] 2019-08-30 10:02
Yes, that's fine.

**Comment by kazk** [comment] 2019-08-31 00:57
@nomennescio Created https://github.com/Codewars/testest and got Circle CI configured. I also invited you as a collaborator with `write` access like ttester repo.

---

I'm planning to allow authors to set vocabulary name to whatever that fits the kata. I'm assuming I can extract the name from the `IN:` line.

So
```factor
IN: preloaded
```
```factor
USE: math
IN: example

: solution ( a b -- a*b ) * ;
```
```factor
USING: preloaded example tools.testest ;
IN: example.tests
```
will be structured like
```
.
├── example
│   ├── example.factor
│   └── tests
│       └── tests.factor
└── preloaded
    └── preloaded.factor
```
under a directory in `FACTOR_ROOTS`.

**Comment by kazk** [comment] 2019-08-31 02:29
Got it working. I'll enable it on Codewars during the weekend if I have the time or early next week and close this.

**Comment by kazk** [comment] 2019-09-04 00:20
Deployed

**Closed by kazk** 2019-09-04 00:20 UTC
Labels: request/language

**Comment by nomennescio** [comment] 2019-09-05 20:42
Awesome! Thanks @kazk

**Comment by g964** [comment] 2019-09-06 08:29
Sorry if it's not the good place for this:

when trying a translation for Factor at CW I used "." to display the last element of the stack as I do with Factor UI. I got:
`No word named “.” found in current vocabulary search path`.
Same thing with ".s". What should I do?

**Comment by nomennescio** [comment] 2019-09-06 09:52
In general: start up Factor on your PC, open the Browser ('Help'), search for a word, read the documentation, find the correct vocabulary to include. Done.

**Comment by nomennescio** [comment] 2019-09-06 09:53
Alternatively: use the [online documentation](https://docs.factorcode.org/content/article-handbook.html)

**Comment by nomennescio** [comment] 2019-09-06 10:09
And to get you going, most certainly view the [Factor presentation by Slava Pestov](https://youtu.be/f_0QlhYlS8g), it's mindblowing (although a bit outdated compared to the latest Factor release, 10 years later...).

**Comment by g964** [comment] 2019-09-06 10:38
Thanks for your work, I read (maybe a bit fast) all that. 
But the problem is: in my PC when using *your* solution to "potatoes" or mine if I write
 ` blah ... blah dup . ;`  it works 
The same thing at CW gives:                                                                     
`No word named “.” found in current vocabulary search path`. Is that clear or I badly explain?

**Comment by g964** [comment] 2019-09-06 11:49
It works if I add ` USING: prettyprint ;`.

**Comment by g964** [comment] 2019-09-06 12:09
I found a way...

**Comment by Voileexperiments** [comment] 2019-09-09 06:44
> `No word named “.” found in current vocabulary search path`

It's in the `prettyprint` vocab:

https://docs.factorcode.org/content/word-.,prettyprint.html
https://docs.factorcode.org/content/vocab-prettyprint.html

I dunno, maybe we can import `prettyprint` by default if it's possible.

**Comment by g964** [comment] 2019-09-09 08:13
@Voileexperiments : thanks.
> maybe we can import prettyprint by default if it's possible

OK.

**Comment by nomennescio** [comment] 2019-09-09 11:59
Factor has well-defined default vocabularies; prettyprint is not in them.
Just USE: it in your code.

Tip: if you run your code in the Factor Listener, it will output EXACTLY the USING: statement you need to import all your libraries for your program.
