### ISSUE TITLE
First character isn't printed in Rust 1.33

### ISSUE THREAD

**Issue by error256** [Codewars/codewars-runner-cli#738] opened 2019-05-09 10:30 UTC
https://www.codewars.com/kumite/5cd3ff7e8b47bb001982deaa
```rust
println!("qwerty");
println!("asdfgh");
```
shows
```
werty
asdfgh
```
in Rust 1.33 (and only in 1.33).

**Comment by kazk** [comment] 2019-05-09 17:42
Thanks for always including Kumite showing the bug, it's extremely helpful.

Looks like this is caused by Rust 1.33's output lacking a tab character (`\t`) in front of the first line unlike previous versions.
I'll close this when the fix is deployed.

**Comment by kazk** [comment] 2019-05-10 04:54
Fixed

**Closed by kazk** 2019-05-10 04:54 UTC
Labels: area/output, kind/bug
