### ISSUE TITLE
[C#] CW Runner outputs TestFixtures in a alphanumerically sorted, cascading pattern

### ISSUE THREAD

**Issue by Souzooka** [Codewars/codewars-runner-cli#496] opened 2017-08-11 10:40 UTC
For example: [this output](http://i.imgur.com/kqoUt3H.jpg) is output by this code:

![image](https://user-images.githubusercontent.com/639336/29296101-0312b842-810d-11e7-93ac-8c83485d690e.png)
```csharp
namespace YourTickerInterpreter {
  using NUnit.Framework;
  using System;
  using System.Collections.Generic;

  [TestFixture, Description("Your Ticker Interpreter")] // NUnit docs says this should work, why is NUnit being difficult
  public class ShouldPassASampleTest
  {
  
    private static IEnumerable<TestCaseData> testCases
    {
      get
      {
        yield return new TestCaseData("")
                                     .Returns("")
                                     .SetDescription("Your interpreter should work for the example program provided in the Description");
      }
    }  
    
    [Test, TestCaseSource("testCases")]
    public string Test(string test)
    {
      return "";
    }
  }
  
  [TestFixture]
  public class ShouldIgnoreNonCommandCharacters
  {
    private static IEnumerable<TestCaseData> testCases
    {
      get
      {
        yield return new TestCaseData("")
                                     .Returns("")
                                     .SetDescription("Your interpreter should ignore whitespace characters");
      }
    }
    
    [Test, TestCaseSource("testCases")]
    public string Test(string test)
    {
      return "";
    }
  }
  
  [TestFixture]
  public class dontactdumb
  {
    [Test]
    public void test(){}
  }
}
```

The runner should display the tests in a flat pattern (e.g. like mocha/chai's describe/it).

---

EDIT: added copy of the linked image and syntax tag

**Comment by kazk** [comment] 2017-08-15 01:08
This is caused by `<DESCRIBE::>` not properly closed by `<COMPLETEDIN::>`.

```csharp
namespace Codewars {
  using NUnit.Framework;
  [TestFixture]
  public class AdderTest1 {
    [Test]
    public void AddingNumbers() {
      Assert.AreEqual(2, Adder.Add(1, 1));
    }
  }
  [TestFixture]
  public class AdderTest2 {
    [Test]
    public void AddingNumbers() {
      Assert.AreEqual(4, Adder.Add(2, 2));
    }
  }
}
```

outputs (leading spaces by me)

```
<DESCRIBE::>Codewars.AdderTest1
  <IT::>AddingNumbers
    <PASSED::>Test Passed
  <COMPLETEDIN::>0.044595

<DESCRIBE::>Codewars.AdderTest2
  <IT::>AddingNumbers
    <PASSED::>Test Passed
  <COMPLETEDIN::>0.000176
```

So every `TestFixture` introduces a new level :(

```
<DESCRIBE::>
  <IT::>
    <PASSED::>
  <COMPLETEDIN::>
  <DESCRIBE::>
    <IT::>
      <PASSED::>
    <COMPLETEDIN::>
    <DESCRIBE::>
      <IT::>
        <PASSED::>
      <COMPLETEDIN::>
      <DESCRIBE::>
        <IT::>
          <PASSED::>
        <COMPLETEDIN::>
```

@jhoffner
I think this can be fixed by adjusting `frameworks/csharp/nunit/EventCollector.cs`, but this requires you to compile like #411. Can you give me some details why it's setup like this? Do you customize NUnit?

**Comment by jhoffner** [comment] 2017-08-15 01:18
This was originally done a long time ago as a hacky and quick and dirty way of getting NUnit to work. There were 2 main issues with NUnit (back then at least, not sure if the latest has resolved these). 

1. NUnit didn't support custom listeners
2. NUnit liked to split STDOUT apart from the actual test output, so we couldn't just parse the output and convert to the custom format.

I added the files to the project for reference and so that we could eventually autocompile them within the project, but currently I still need to compile the code on my local. I had timeboxed a day or 2 to upgrade our C#'s implementation but ran out of time. I also had started to look into .NET Core but also fell short on time.

So the basic fix for this is easy but I think its priority isn't so high that we need to kick the can down the street again - Let's address this issue properly when you have time to flesh out a better C# runner implementation. What exists now is too hacky.

**Comment by kazk** [comment] 2018-08-10 00:40
C# 7.3 with NUnit 3 is released. We're going to remove the old one once we update some contents.
The output with NUnit 3 should be correct and you can also use `Description` attribute. Note that `TestCaseSource` no longer takes string on NUnit 3 so you'll need to update that.

**Closed by kazk** 2018-08-10 00:40 UTC
Labels: area/output, language/csharp
