### ISSUE TITLE
BASIC Support

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars-runner-cli#157] opened 2016-05-24 21:25 UTC
Perhaps you can add some old fashion BASIC programming language support by adding some Java based interpreter like [JBasic](https://sourceforge.net/projects/jbasic/) trough java-runner.

**Comment by javatlacati** [comment] 2018-12-08 21:18
Visual Basic is part now of the new opensource Microsoft's wave and [roslyn](https://github.com/dotnet/roslyn) can be used to compile it.

**Comment by kazk** [comment] 2019-01-22 08:16
Closing as duplicate of #155 then.

**Closed by kazk** 2019-01-22 08:16 UTC
Labels: request/language
