### ISSUE TITLE
Missing std::make_reverse_iterator

### ISSUE THREAD

**Issue by lvlsun** [Codewars/codewars-runner-cli#563] opened 2018-01-11 19:16 UTC
[std::make_reverse_iterator](http://en.cppreference.com/w/cpp/iterator/make_reverse_iterator) is defined in C++14 standard but:
```
-isystem /runner/frameworks/cpp/  error: no member named 'make_reverse_iterator' in namespace 'std'
        for (auto j=std::make_reverse_iterator(i); j!=v.rend(); ++j)
                    ~~~~~^
1 error generated.
```
Is this a bug?

**Comment by kazk** [comment] 2018-01-11 20:11
Thanks for reporting.

[All of C++14 is supported](http://clang.llvm.org/cxx_status.html#cxx14) since Clang 3.4 so I think this is a bug. Probably caused by using `-std=c++1y` instead of `-std=c++14`:

https://github.com/Codewars/codewars-runner-cli/blob/dbf943d62c8d6ed451d27ac1817c0f13b1de558c/lib/runners/cpp.js#L58

We'll look into it.

**Comment by kazk** [comment] 2018-01-28 05:07
Changing the flag doesn't fix the issue, so I started to look into this deeper.
I think this is caused by outdated `libc++` from `libc++-dev`.
https://github.com/Codewars/codewars-runner-cli/blob/dbf943d62c8d6ed451d27ac1817c0f13b1de558c/docker/systems.docker#L18

---

Snippet from [How to check if libc++ is installed?](https://stackoverflow.com/questions/38441490/how-to-check-if-libc-is-installed) shows the version:
```
printf "#include <ciso646>\nint main () {}" \
  | clang-3.6 -E -stdlib=libc++ -x c++ -dM - \
  | grep _LIBCPP_VERSION

#define _LIBCPP_VERSION 1101
```

**Comment by kazk** [comment] 2018-03-03 00:07
This is caused by the outdated `libc++` and is fixed in the new runner. I'll close this issue after the migration.

**Closed** 2018-04-04 19:13 UTC
Labels: bug, language/cpp, status/on-hold
