### ISSUE TITLE
Server Execution Error "Unexpected token { in JSON at position 1240339"

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars-runner-cli#398] opened 2017-04-24 23:01 UTC
@simonvpe commented on [Fri Feb 24 2017](https://github.com/Codewars/codewars.com/issues/843)

I get these errors a lot. Sometimes only on the "Run Examples" build, and sometimes on the "Attempt" build. If i change a line, or add/remove a write to stdout it changes to either not appear at all, or to appear on only one of the builds.

Sometimes I get HTTP 5xx errors or timeouts saying that I write too much to stdout (even though I don't).

This Kata is runs very heavy optimization tests so it's kind of taxing on the servers, is this the issue? Should there be more robust error handling when the server can't cope with the load?

I might add that I can build about one in tweny times so it is very time consuming and ruins the experience completely!

BR Simon

---

@menip commented on [Sun Feb 26 2017](https://github.com/Codewars/codewars.com/issues/843#issuecomment-282574308)

I'm having the same issue with the [longest_palindrome](https://www.codewars.com/kata/54bb6f887e5a80180900046b/train/python) kata. My code:
```python
def longest_palindrome (s):
    longest = 0
    for i in range(len(s)):
        si = s[i:]
        for j in range(len(si)):
            sj = si[:j+1]
            if sj == sj[::-1] and longest < len(sj): 
                    longest = len(sj)
    return longest
```

EDIT: Was able to attempt and submit without issue after an hour passed. 

---

@ioncrash commented on [Wed Mar 08 2017](https://github.com/Codewars/codewars.com/issues/843#issuecomment-285206522)

I've been getting similar errors continuously for about an hour. Position number seems to be different every time I run it

---

@Khanthulhu commented on [Mon Apr 24 2017](https://github.com/Codewars/codewars.com/issues/843#issuecomment-296845184)

Having the same problem with Simple Fun #27: Rectangle Rotation. The position changes each time I submit.

**Comment by Khanthulhu** [comment] 2017-04-24 23:15
I removed the puts statements from my code and now I don't have a problem. I think it might have to do with the large number of output my program had.

**Comment by jhoffner** [comment] 2017-04-24 23:17
yeah it's definitely caused by that. This is a bug in that somehow the message telling you that your output is too long is not properly being massaged.

**Comment by kazk** [comment] 2017-05-03 01:36
@jhoffner
Are you using `opts.format=json` and parsing the entire output as `JSON`?
Something similar happened to me when I was running tests using `run-json`.
`JSON.parse(buffer)` failed because `buffer` contained logs I had inserted, like `JSON.parse('"some info"\n{"stdout": "", "stderr": ""}')`.

---

I found `opts.publish` at [lib/shovel.js#L222](https://github.com/Codewars/codewars-runner-cli/blob/815480438a336443327e850a2c9e51eaae8e4989/lib/shovel.js#L222) is missing `event` (should be `opts.publish('stdout', msg)`?).

![image](https://cloud.githubusercontent.com/assets/639336/25645357/1138b824-2f62-11e7-891e-79160ccbc898.png)

This can be the cause if that function prints something, like a warning.

**Comment by jhoffner** [comment] 2017-05-03 01:40
@kazk Good catch, we should fix that - though I don't think that's the cause of this issue. opts.publish will send a websocket response back to the client, it doesn't get routed through STDOUT at all.

**Comment by kazk** [comment] 2017-05-03 01:45
I meant the case when Ably's `channel.publish(event, data);` logged some warning for calling `channel.publish(msg, undefined);`.
Wouldn't that write to `stdout`?

**Comment by jhoffner** [comment] 2017-05-03 01:55
Ohhh. Ok really good catch! That also makes me wonder if we should either try to replace Ably's internal log method, or wrap console.log ourselves and do our own writes directly with `process.stdout.write`.

**Comment by kazk** [comment] 2017-05-03 02:19
I just scanned through the `Ably.Rest`'s options and found one for logging.
I'm not familiar with Ably, so I might be completely wrong, but disabling logs by using this

```javascript
var ably = new require('ably').Rest({
  key: opts.ably,
  log: {level: 0}
});
```

might work? `log` can also take `handler` function.

> log
> Parameters to control the log output of the library.
> The supplied value must be an object that may contain one or both of the following entries:
> - `level`: a number controlling the verbosity of the output. Valid values are: 0 (no logs), 1 (errors only), 2 (errors plus connection and channel state changes), 3 (high-level debug output), and 4 (full debug output).
> - `handler`: a function to handle each line of log output. If handler is not specified, `console.log` is used.
>
> Note that the log level and log handler have global scope in the library and will thus not act independently between library instances when multiple library instances exist concurrently.
>
> <https://www.ably.io/documentation/realtime/usage#client-options>

**Comment by kazk** [comment] 2017-05-03 02:29
Maybe not. I missed that it's **client** options :(

**Comment by jhoffner** [comment] 2017-05-03 02:31
I think that will do it. There is no client vs server, I'm assuming it's the same options.

**Comment by kazk** [comment] 2018-01-31 20:11
Closing this because I believe #408 fixed the issue.

**Closed by kazk** 2018-01-31 20:11 UTC
Labels: bug
