### ISSUE TITLE
Agda code runner output sometimes are not formatted properly

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars-runner-cli#731] opened 2019-03-25 07:23 UTC
Compare this:
![image](https://user-images.githubusercontent.com/14909989/54901507-9b4c0680-4f11-11e9-9a16-be2d4c49e97b.png)

to this:
![image](https://user-images.githubusercontent.com/14909989/54901543-bb7bc580-4f11-11e9-87f3-e86128bfec54.png)

The problem: the former is in a bad formatting. It also defaults to *collapsing* the block, which is extremely inconvenient as I'd have to open the block every time to see the error message.

**Comment by kazk** [comment] 2019-03-25 07:43
Thanks for reporting. This is exactly what I meant when said I [needed help testing the output](https://github.com/Codewars/codewars-runner-cli/issues/719#issuecomment-471415288).

The post processing is failing because it has extra `,38` at the end. It currently assumes

```
/path/to/module.agda:line,from_col-to_col
error message line 1
error message line 2
...
```

**Comment by kazk** [comment] 2019-03-27 03:46
This should be fixed now. Please let me know if it's not with some code to reproduce.

**Closed by kazk** 2019-03-27 03:46 UTC
Labels: area/output, kind/bug, language/agda
