### ISSUE TITLE
Confusing handling of Haskell code with no module declaration

### ISSUE THREAD

**Issue by benzrf** [Codewars/codewars-runner-cli#272] opened 2016-11-10 15:15 UTC
When a chunk of Haskell code gets saved to a file, it looks like the file name is decided based on the module declaration (which is reasonable!). However, if there's no module declaration, you don't get an error message - it just tries to use `undefined.hs`. I forgot to add module declarations while writing a kata, and I was extremely confused when I got a mysterious error telling me that a file could not be written because it already existed - turns out it tried to reuse `undefined.hs` for both the solution and the test cases. I think it would be a lot more helpful to give a warning message when your Haskell doesn't have a module declaration - maybe one that explains the possibility of filename overlaps.

**Comment by kazk** [comment] 2017-08-18 21:44
I'm going to close this because I'm unable to reproduce. I think this is because https://github.com/Codewars/codewars-runner-cli/commit/8af75521e15e44fd27b417b708146b2488b7b096 changed the behavior of `util.codeWriteSync` to overwrite unless explicitly specified not to.

When the solution lacks module declaration, it defaults to `Main`. When the test lacks module declaration, it defaults to `Main` unless solution's path ends with `Main.hs`, in that case the test module will be `undefined`. So I think this used to only happen when preloaded code (`opts.setup`) also lacked module declaration.

I don't think current implementation is user friendly (overwriting preloaded code with test), but preloaded code requires module declaration to be used so this shouldn't happen too often. Haskell runner needs some rework and I'll try to make this better when I get to it.

**Closed by kazk** 2017-08-18 21:44 UTC
Labels: help required
